setwd('D:/Mike/Documents/Jean Marie Lab/yelpdata')
load('wordcloudbigrandomsample.RData')
onem$word<-as.character(onem$word)
twom$word<-as.character(twom$word)
threem$word<-as.character(threem$word)
fourm$word<-as.character(fourm$word)
fivem$word<-as.character(fivem$word)
dataset<-dataset$stars
onem<-m[dataset==1,]
word_freqs <- colSums(onem) 
onem <- data.frame(word=names(word_freqs), freq=word_freqs)
twom<-m[dataset==2,]
word_freqs <- sort(colSums(twom), decreasing=TRUE) 
twom <- data.frame(word=names(word_freqs), freq=word_freqs)
threem<-m[dataset==3,]
word_freqs <- sort(colSums(threem), decreasing=TRUE) 
threem <- data.frame(word=names(word_freqs), freq=word_freqs)
fourm<-m[dataset==4,]
word_freqs <- sort(colSums(fourm), decreasing=TRUE) 
fourm <- data.frame(word=names(word_freqs), freq=word_freqs)
fivem<-m[dataset==5,]
word_freqs <- sort(colSums(fivem), decreasing=TRUE) 
fivem <- data.frame(word=names(word_freqs), freq=word_freqs)
library(dplyr)
onetwo<-inner_join(onem,twom,by="word")
onetwo<-data.frame(onetwo,rep(1,nrow(onetwo)))
colnames(onetwo)<-c('word','x.freq','y.freq','dist')
onethree<-inner_join(onem,threem,by="word")
onethree<-data.frame(onethree,rep(2,nrow(onethree)))
colnames(onethree)<-c('word','x.freq','y.freq','dist')
onefour<-inner_join(onem,fourm,by="word")
onefour<-data.frame(onefour,rep(3,nrow(onefour)))
colnames(onefour)<-c('word','x.freq','y.freq','dist')
onefive<-inner_join(onem,fivem,by="word")
onefive<-data.frame(onefive,rep(4,nrow(onefive)))
colnames(onefive)<-c('word','x.freq','y.freq','dist')
twothree<-inner_join(twom,threem,by="word")
twothree<-data.frame(twothree,rep(1,nrow(twothree)))
colnames(twothree)<-c('word','x.freq','y.freq','dist')
twofour<-inner_join(twom,fourm,by="word")
twofour<-data.frame(twofour,rep(2,nrow(twofour)))
colnames(twofour)<-c('word','x.freq','y.freq','dist')
twofive<-inner_join(twom,fivem,by="word")
twofive<-data.frame(twofive,rep(3,nrow(twofive)))
colnames(twofive)<-c('word','x.freq','y.freq','dist')
threefour<-inner_join(threem,fourm,by="word")
threefour<-data.frame(threefour,rep(1,nrow(threefour)))
colnames(threefour)<-c('word','x.freq','y.freq','dist')
threefive<-inner_join(threem,fivem,by="word")
threefive<-data.frame(threefive,rep(2,nrow(threefive)))
colnames(threefive)<-c('word','x.freq','y.freq','dist')
fourfive<-inner_join(fourm,fivem,by="word")
fourfive<-data.frame(fourfive,rep(1,nrow(fourfive)))
colnames(fourfive)<-c('word','x.freq','y.freq','dist')
rm(list=c('onem','twom','threem','fourm','fivem'))


combined<-rbind(onetwo,onethree,onefour,onefive,twothree,twofour,twofive,threefour,threefive,fourfive)
corlist<-mutate(combined,corxy=dist*(1-abs(x.freq-y.freq)/(x.freq+y.freq)))
corlist$word<-as.factor(corlist$word)

wordCor<-aggregate(formula=corxy~word,data=corlist,FUN=sum)

save(wordCor,file='wordCorBigRandomSample.RData')
